let val = 
[
    {
        "Unnamed: 0": 417,
        "RecipeId": 496,
        "Name": "7-Up Cake",
        "CookTime": "PT42M",
        "PrepTime": "PT45M",
        "TotalTime": "PT1H27M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/49/6/piclJbARg.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"1\", \"2/3\", \"4\", \"10\", \"1/2\", \"1 1/2\", \"1\", \"2\", NA, \"2\")",
        "RecipeIngredientParts": "c(\"pineapple instant pudding\", \"eggs\", \"margarine\", \"sugar\", \"crushed pineapple\", \"flour\", \"angel flake coconut\", \"eggs\")",
        "Calories": 550.2,
        "FatContent": 24.5,
        "SaturatedFatContent": 4.5,
        "CholesterolContent": 93.0,
        "SodiumContent": 442.4,
        "CarbohydrateContent": 78.7,
        "FiberContent": 0.9,
        "SugarContent": 39.0,
        "ProteinContent": 5.6,
        "RecipeInstructions": "c(\"Empty lemon supreme cake mix and instant pineapple pudding into a large mixing bowl.\", \"Add oil and eggs.\", \"Beat about 2 minutes.\", \"Add 7-Up and mix until well blended.\", \"Pour into a greased and floured cake sheet pan.\", \"Preheat oven to 350 degrees Fahrenheit.\", \"Bake 35 to minutes or until done.\", \"While still hot spread with Icing.\", \"ICING:\", \"Cook margarine, sugar, pineapple, flour and eggs until thick.\", \"Add coconut and blend well.\", \"Spread over cake while both are still warm.\")"
    },
    {
        "Unnamed: 0": 6716,
        "RecipeId": 9830,
        "Name": "7 Up Cake",
        "CookTime": "PT1H25M",
        "PrepTime": "PT10M",
        "TotalTime": "PT1H35M",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/98/30/picKfuy6n.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1 1/2\", \"3\", \"5\", \"3\", \"2\", \"3/4\")",
        "RecipeIngredientParts": "c(\"butter\", \"sugar\", \"eggs\", \"flour\")",
        "Calories": 411.2,
        "FatContent": 19.0,
        "SaturatedFatContent": 11.5,
        "CholesterolContent": 103.9,
        "SodiumContent": 176.0,
        "CarbohydrateContent": 56.7,
        "FiberContent": 0.6,
        "SugarContent": 38.6,
        "ProteinContent": 4.6,
        "RecipeInstructions": "c(\"Cream butter and sugar until light and fluffy.\", \"Add eggs one at a time, beating well after each addition.\", \"Stir in flour; beat in lemon extract and 7Up.\", \"Pour batter into well greased and floured 12 cup fluted mold.\", \"Bake at 325 degrees for 60 minutes to an hour and 25 minutes.\", \"Cool; dust with conf.\", \"sugar if desired.\")"
    },
    {
        "Unnamed: 0": 236884,
        "RecipeId": 246661,
        "Name": "Apple Cake",
        "CookTime": "PT55M",
        "PrepTime": "PT15M",
        "TotalTime": "PT1H10M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/24/66/61/picYQU7rf.jpg\"",
        "RecipeCategory": "Breakfast",
        "RecipeIngredientQuantities": "c(\"5\", \"1/3\", \"1\", \"2\", \"4\", \"1/2\", \"1\", \"1\", \"3\", \"1 1/2\", \"1/4\")",
        "RecipeIngredientParts": "c(\"apples\", \"granulated sugar\", \"cinnamon\", \"granulated sugar\", \"eggs\", \"vanilla extract\", \"all-purpose flour\", \"baking powder\", \"salt\")",
        "Calories": 372.6,
        "FatContent": 15.2,
        "SaturatedFatContent": 2.2,
        "CholesterolContent": 46.5,
        "SodiumContent": 89.8,
        "CarbohydrateContent": 56.2,
        "FiberContent": 2.1,
        "SugarContent": 36.0,
        "ProteinContent": 4.2,
        "RecipeInstructions": "c(\"Preheat the oven to 350°F Grease an 11 x 9\\\" cake pan.\", \"Combine sugar and cinnamon in a small bowl. Set aside.\", \"In a large bowl, beat together the sugar, eggs, apple juice, oil and vanilla until well blended.\", \"In a separate bowl, combine the flour, baking powder and salt. Add the dry mixture to the egg mixture and mix well.\", \"Spread half of the batter into the prepared pan. Evenly sprinkle the chopped apple over the batter. Evenly sprinkle half of the cinnamon sugar over the apples. Then, spread the rest of the batter evenly over the cinnamon and finish with sprinkling the rest of the cinnamon sugar over the second layer of batter.\", \n\"Bake for 50 to 60 minutes. Serve warm or cold.\")"
    },
    {
        "Unnamed: 0": 280003,
        "RecipeId": 291057,
        "Name": "Apple Cake",
        "CookTime": "PT30M",
        "PrepTime": "PT10M",
        "TotalTime": "PT40M",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/29/10/57/pictNMpWA.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"2\", \"1\", \"3\", \"3\", \"2\", \"1\", \"2\")",
        "RecipeIngredientParts": "c(\"self raising flour\", \"sugar\", \"egg\", \"butter\", \"milk\", \"apples\", \"cinnamon\", \"sugar\")",
        "Calories": 313.0,
        "FatContent": 10.7,
        "SaturatedFatContent": 6.2,
        "CholesterolContent": 71.0,
        "SodiumContent": 101.1,
        "CarbohydrateContent": 50.2,
        "FiberContent": 3.4,
        "SugarContent": 22.2,
        "ProteinContent": 5.5,
        "RecipeInstructions": "c(\"Preheat oven to 180 degree celsius.\", \"Grease pie plate.\", \"Sift flour with and sugar and then add the egg, melted butter and milk and mix well.\", \"Pour mix into greased pie plate.\", \"Mix cinnamon and sugar together.\", \"Arrange sliced apples on top and sprinkle with sugar and cinnamon mix.\", \"Bake in oven for 30 minutes or until a skewer comes out clean once pierced.\")"
    },
    {
        "Unnamed: 0": 403343,
        "RecipeId": 418117,
        "Name": "Lemon Cake",
        "CookTime": "PT35M",
        "PrepTime": "PT10M",
        "TotalTime": "PT45M",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/41/81/17/pichdsEOp.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"2\", \"1/2\", \"3\", \"1\", \"1\", \"2 1/4\", \"6\")",
        "RecipeIngredientParts": "c(\"eggs\", \"water\", \"powdered sugar\", \"lemon juice\")",
        "Calories": 429.2,
        "FatContent": 15.3,
        "SaturatedFatContent": 2.3,
        "CholesterolContent": 53.7,
        "SodiumContent": 367.5,
        "CarbohydrateContent": 69.7,
        "FiberContent": 0.5,
        "SugarContent": 53.2,
        "ProteinContent": 4.6,
        "RecipeInstructions": "c(\"Preheat oven to 350 F.\", \"Make cake batter with the jello, oil, eggs and lemon extract.\", \"Bake @ 350 for 35 min in a large cake pan.\", \"While the cake is cooking prepare the frosting mixture with the powdered sugar mixed with the juice of 3 lemons or 6 Tablespoon of lemon juice.\", \"When done, poke cake full of holes with a fork, and drizzle frosting mixture all over the cake.\")"
    },
    {
        "Unnamed: 0": 414872,
        "RecipeId": 430075,
        "Name": "Lemon Cake",
        "CookTime": "PT25M",
        "PrepTime": "PT25M",
        "TotalTime": "PT50M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/43/00/75/pic5xQDtZ.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"3\", \"1/4\", \"1\", \"1\", \"1\", \"2\", \"4\", \"1 1/2\", \"1\", \"1 1/2\", \"1/4\")",
        "RecipeIngredientParts": "c(\"all-purpose flour\", \"salt\", \"baking soda\", \"baking powder\", \"unsalted butter\", \"sugar\", \"eggs\", \"buttermilk\", \"fresh lemon juice\", \"lemon zest\")",
        "Calories": 156.5,
        "FatContent": 6.6,
        "SaturatedFatContent": 3.9,
        "CholesterolContent": 42.1,
        "SodiumContent": 113.4,
        "CarbohydrateContent": 22.2,
        "FiberContent": 0.3,
        "SugarContent": 13.1,
        "ProteinContent": 2.4,
        "RecipeInstructions": "c(\"Preheat the oven to 350 degrees.\", \"Place flour, salt, baking soda, and baking powder into a sifter and sift into a bowl.\", \"In a separate mixing bowl, cream butter.\", \"While the butter is mixing, add sugar until combined.\", \"In a small bowl, whisking eggs; slowly add to butter mixture on low speed.\", \"Slowly add in a 1/4 the flour mix - keep the mixer going then add a 1/4 the buttermilk. Keep mixing, then add another 1/4 of each again at different times, keep mixing and keep repeating until you have used up both the flour mix and buttermilk (start with flour, and end with flour).\", \n\"Add lemon juice, lemon extract, and lemon zest until combined.\", \"Evenly distribute the cake batter into baking pans. (I used 4 8-inch.).\", \"Once the oven has been preheat, bake the cakes for 25 minutes or until done.\")"
    },
    {
        "Unnamed: 0": 99400,
        "RecipeId": 104928,
        "Name": "Banana Cake",
        "CookTime": "PT50M",
        "PrepTime": "PT20M",
        "TotalTime": "PT1H10M",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/10/49/28/pic8gQVTk.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"3\", \"1\", \"1\", \"3/4\", \"3/4\", \"2 1/4\", \"3\", \"6\", \"1 1/2\")",
        "RecipeIngredientParts": "c(\"flour\", \"baking powder\", \"baking soda\", \"salt\", \"shortening\", \"sugar\", \"eggs\", \"buttermilk\", \"bananas\")",
        "Calories": 4923.2,
        "FatContent": 173.7,
        "SaturatedFatContent": 44.4,
        "CholesterolContent": 638.1,
        "SodiumContent": 3680.1,
        "CarbohydrateContent": 794.0,
        "FiberContent": 16.0,
        "SugarContent": 483.6,
        "ProteinContent": 63.0,
        "RecipeInstructions": "c(\"Preheat oven to 350 degrees.\", \"Sift dry ingredients together, set aside.\", \"Cream shortening and sugar.\", \"Add eggs and buttermilk to sugar mixture.\", \"Combine dry ingredients into wet.\", \"When incorporated, stir in mashed banana.\", \"Pour batter into a greased, floured tube pan (angel food cake pan).\", \"Bake 45-50 minutes, or until a toothpick inserted in center of cake comes out clean.\", \"Cool slightly, run knife around edges of pan to loosen cake, remove cake from pan.\", \"Finish cooling cake on a wire rack.\", \n\"Slice into wedges.\")"
    },
    {
        "Unnamed: 0": 187306,
        "RecipeId": 195704,
        "Name": "Banana Cake",
        "CookTime": "PT40M",
        "PrepTime": "PT30M",
        "TotalTime": "PT1H10M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/19/57/04/picNXZbTJ.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"3/4\", \"1/2\", \"1/4\", \"3\", \"1/4\", \"1\", \"2\", \"1/4\", \"1 1/2\", \"1\", \"2\", \"1/4\", \"1\", \"1/4\", \"1 1/2\")",
        "RecipeIngredientParts": "c(\"raisins\", \"water\", \"butter\", \"powdered milk\", \"bananas\", \"water\", \"vanilla\", \"eggs\", \"flour\", \"baking soda\", \"cinnamon\", \"clove\", \"salt\", \"lemon juice\", \"baking powder\")",
        "Calories": 278.4,
        "FatContent": 13.2,
        "SaturatedFatContent": 7.0,
        "CholesterolContent": 69.8,
        "SodiumContent": 530.1,
        "CarbohydrateContent": 36.7,
        "FiberContent": 2.5,
        "SugarContent": 14.5,
        "ProteinContent": 5.6,
        "RecipeInstructions": "c(\"Boil raisins and water together to get 1/4 cup raisin juice.\", \"Cream together butter and and powdered milk.\", \"Add bananas, raisin water, vanilla, lemon juice eggs and finely chopped nuts.\", \"Blend in dry ingredients bake in 9x10-inch cake pan at 350° for 30-40 minutes.\")"
    },
    {
        "Unnamed: 0": 353758,
        "RecipeId": 366773,
        "Name": "Banana Cake",
        "CookTime": "PT45M",
        "PrepTime": "PT15M",
        "TotalTime": "PT1H",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/36/67/73/picoRPwGX.jpg\"",
        "RecipeCategory": "Breads",
        "RecipeIngredientQuantities": "c(\"60\", \"2/3\", \"1\", \"2\", \"1\", \"1 1/2\", \"1/2\")",
        "RecipeIngredientParts": "c(\"butter\", \"sugar\", \"vanilla essence\", \"bananas\", \"egg\", \"self-raising flour\", \"milk\")",
        "Calories": 494.8,
        "FatContent": 15.1,
        "SaturatedFatContent": 8.9,
        "CholesterolContent": 82.8,
        "SodiumContent": 735.5,
        "CarbohydrateContent": 83.3,
        "FiberContent": 2.8,
        "SugarContent": 40.8,
        "ProteinContent": 8.0,
        "RecipeInstructions": "c(\"Preheat oven to 180°C.\", \"Beat butter and sugar until light and creamy.\", \"Add mashed banana.\", \"Add egg gradually beating after each addition.\", \"Add essence.\", \"Fold in sifted flour alternately with milk.\", \"Stir until just combined and mixture is smooth.\", \"Bake in a 9x23 cm oiled loaf tin for 45 minutes or till skewer comes out clean.\", \"Leave cake in tin for 5 minutes, thank turn onto a wire rack to cool.\")"
    },
    {
        "Unnamed: 0": 490202,
        "RecipeId": 508270,
        "Name": "Carrot Cake",
        "CookTime": "PT30M",
        "PrepTime": "PT20M",
        "TotalTime": "PT50M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/50/82/70/picPlzc5p.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"1\", \"3/4\", \"4\", \"2\", \"2\", \"2\", \"2\", \"1\", \"3\", \"1\", \"1/4\", \"4\", \"1\")",
        "RecipeIngredientParts": "c(\"canola oil\", \"granulated sugar\", \"brown sugar\", \"eggs\", \"cinnamon\", \"baking soda\", \"baking powder\", \"salt\", \"carrots\", \"cream cheese\", \"butter\", \"icing sugar\", \"vanilla extract\")",
        "Calories": 422.1,
        "FatContent": 21.9,
        "SaturatedFatContent": 8.9,
        "CholesterolContent": 70.1,
        "SodiumContent": 457.9,
        "CarbohydrateContent": 56.0,
        "FiberContent": 0.8,
        "SugarContent": 53.5,
        "ProteinContent": 2.7,
        "RecipeInstructions": "c(\"Preheat oven to 350°F (180°C) and grease two 9” (23cm) cake pans. Beat oil and sugars together in a large bowl until combined. Add eggs, one at a time, beating well after each addition. Next, combine flour, cinnamon, baking soda, baking powder and salt in a separate large bowl. Add flour mixture to egg mixture. Mix, just until combined. Fold in carrots. Divide batter evenly in prepared pans. Bake in preheated oven 25 to 30 minutes or until a toothpick inserted in centre of cake comes out clean. Cool in pans on wire cooling rack for 20 minutes. Remove from pans and cool completely on wire cooling rack.\", \n\"For icing, cream butter and cream cheese in a medium bowl. Add icing sugar, one cup (250mL) at a time. Beat well after each addition. Add vanilla. Continue beating until fluffy. Add 1 tbsp (15mL) milk at a time to thin out icing if necessary. Place one cake on serving dish. Spread with icing. Top with remaining cake layer. Spread top with remaining icing.\", \"These recipes and more are available online at www.robinhood.ca.\")"
    },
    {
        "Unnamed: 0": 233597,
        "RecipeId": 243296,
        "Name": "Carrot Cake",
        "CookTime": "PT45M",
        "PrepTime": "PT45M",
        "TotalTime": "PT1H30M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/24/32/96/picYKJmL8.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"2\", \"2\", \"1\", \"1\", \"1/2\", \"1\", \"1\", \"1\", \"2\", \"1/2\", \"4\", \"3/4\", \"1/4\", \"1\", \"1\", \"1\", \"250\", \"1/4\", \"2\", \"1\", NA)",
        "RecipeIngredientParts": "c(\"extra-large eggs\", \"maple syrup\", \"plain yogurt\", \"lemon juice\", \"vanilla extract\", \"all-purpose flour\", \"salt\", \"baking powder\", \"cinnamon\", \"allspice\", \"pecans\", \"apple\", \"carrot\", \"cream cheese\", \"maple syrup\", \"pecans\")",
        "Calories": 497.8,
        "FatContent": 32.9,
        "SaturatedFatContent": 11.9,
        "CholesterolContent": 128.6,
        "SodiumContent": 321.5,
        "CarbohydrateContent": 45.6,
        "FiberContent": 2.0,
        "SugarContent": 23.7,
        "ProteinContent": 7.5,
        "RecipeInstructions": "c(\"NOTE: The recipe also calls for 1 Tbl Fiber Sure to be added to the ingredient list.  Zaar is not accepting this as an ingredient.\", \"Preheat your oven to 350°F.\", \"Prepare a 13 by 9 pan, lining it with parchment paper (or grease and flour it lightly).\", \"In a large bowl, whip the eggs and egg yolks to a froth.\", \"Add maple syrup, yogurt and oil, mixing well.\", \"*For the lemon juice, heat your lemon under hot water then roll with your hand, with a bit of pressure, on the counter. This helps to release the juice.\", \n\"Measure 1 Tbl of the lemon juice into a small cup along with the extracts and Fiber Sure (or other brand of fiber supplement), mixing well to dissolve the Fiber Sure.\", \"In a separate bowl, mix the flour, salt, baking powder and spices.\", \"Add the pecans, apple and carrot to the dry ingredients.\", \"Blend the dry and wet ingredients without over stirring.\", \"Spoon the batter into the prepared pan and spread evenly.\", \"Bake @ 350F for approximately 45 minutes or till cake tests done (lightly pressed with your finger tip, it should spring back).\", \n\"Cool in the pan for 10 minutes then remove to a wire rack to finish cooling.\", \"Meanwhile, in a clean bowl, whip the cream cheese till creamy.\", \"Add the maple syrup and extract, blending well.\", \"Separately, whip the cream to stiff peaks.\", \"Fold the whipped cream into the cheese mixture to blend without over mixing.\", \"Spread with a light hand over the cooled cake and top with pecans if desired.\", \"Note - cooling time is not included.\")"
    },
    {
        "Unnamed: 0": 64474,
        "RecipeId": 68974,
        "Name": "Carrot Cake",
        "CookTime": "PT10M",
        "PrepTime": "PT10M",
        "TotalTime": "PT20M",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/68/97/4/picXvPQ72.jpg\"",
        "RecipeCategory": "Breads",
        "RecipeIngredientQuantities": "c(\"2\", \"2\", \"1 1/2\", \"1 1/2\", \"2\", \"2\", \"1 1/2\", \"4\", \"2\", \"1\", \"1/2\", \"1\")",
        "RecipeIngredientParts": "c(\"flour\", \"baking powder\", \"baking soda\", \"salt\", \"ground cinnamon\", \"granulated sugar\", \"eggs\", \"raw carrots\", \"crushed pineapple\", \"walnuts\", \"flaked coconut\")",
        "Calories": 844.1,
        "FatContent": 52.5,
        "SaturatedFatContent": 10.1,
        "CholesterolContent": 105.8,
        "SodiumContent": 852.8,
        "CarbohydrateContent": 89.2,
        "FiberContent": 3.3,
        "SugarContent": 61.4,
        "ProteinContent": 8.3,
        "RecipeInstructions": "c(\"Combine and sift together flour, baking powder, soda, salt and cinnamon.\", \"Add sugar, oil and eggs.\", \"Using electric mixer, beat at medium speed 1 minute.\", \"Stir in carrots, pineapple, nuts and coconut.\", \"Pour batter into 3 greased and floured 9-inch cake pans or in a 13x9-inch pan and bake in a 350 oven for 35-40 minutes or until a toothpick comes out clean.\", \"Let cool completely before filling and icing.\")"
    },
    {
        "Unnamed: 0": 16508,
        "RecipeId": 19841,
        "Name": "Carrot Cake",
        "CookTime": "PT50M",
        "PrepTime": "PT10M",
        "TotalTime": "PT1H",
        "Images": "c(\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/19/84/1/TvOnvpOTwKdXtHZ92oko_carrot-cake-natural-cream-cheese-frosting-9015.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1 1/2\", \"3\", \"2\", \"2 1/2\", \"2\", \"2\", \"2\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1 -2\", \"1\")",
        "RecipeIngredientParts": "c(\"eggs\", \"sugar\", \"flour\", \"raw carrots\", \"baking soda\", \"cinnamon\", \"crushed pineapple\", \"salt\", \"cream cheese\", \"margarine\", \"powdered sugar\", \"vanilla\", \"milk\", \"salt\")",
        "Calories": 810.1,
        "FatContent": 42.1,
        "SaturatedFatContent": 8.6,
        "CholesterolContent": 67.4,
        "SodiumContent": 599.5,
        "CarbohydrateContent": 104.5,
        "FiberContent": 2.9,
        "SugarContent": 79.4,
        "ProteinContent": 7.8,
        "RecipeInstructions": "c(\"Mix all cake ingredients together and bake at 350° for 50 minutes in 9x13-inch baking pan.\", \"Blend all icing ingredients well and cover cake generously.\")"
    },
    {
        "Unnamed: 0": 92549,
        "RecipeId": 97902,
        "Name": "Pound Cake",
        "CookTime": "PT1H",
        "PrepTime": "PT20M",
        "TotalTime": "PT1H20M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/97/90/2/pic2x4k70.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1 1/2\", \"1/4\", \"1/4\", \"3/8\", \"1\", \"2\", \"1/2\", \"1 1/4\", \"1/4\", \"1\", \"1\")",
        "RecipeIngredientParts": "c(\"flour\", \"baking powder\", \"baking soda\", \"salt\", \"egg\", \"buttermilk\", \"vanilla\", \"margarine\", \"unsalted butter\", \"sugar\")",
        "Calories": 178.0,
        "FatContent": 5.4,
        "SaturatedFatContent": 1.5,
        "CholesterolContent": 20.6,
        "SodiumContent": 176.9,
        "CarbohydrateContent": 29.3,
        "FiberContent": 0.4,
        "SugarContent": 17.3,
        "ProteinContent": 3.1,
        "RecipeInstructions": "c(\"Have all ingredients at room temperature (70F).\", \"Adjust oven racks to divide oven in thirds; preheat oven to 325°F Spray 5 cup loaf pan, bundt pan or tube pan with nonstick cooking spray.\", \"In small bowl, whisk together flour, baking powder, baking soda, and salt; sift together and set aside.\", \"In small bowl, whisk together egg and egg whites; set aside.\", \"In small bowl, combine buttermilk and vanilla; set aside.\", \"Cut margarine and butter into 1/4\\\" chunks and place in large bowl of electric mixer; beat at medium speed until softened, about 1 minute.\", \n\"Add sugar gradually, beating constantly, until smooth, about 3 minutes.\", \"Gradually dribble in beaten eggs, beating at medium-high speed for 2-3 minutes.\", \"On low speed, beat in 1/3 of the reserved flour mixture, scraping sides of bowl.\", \"On medium-high speed, gradually dribble in 1/2 of the buttermilk mixture, scraping sides of bowl.\", \"On low speed, beat in half of the remaining flour mixture.\", \"On medium-high speed, beat in the rest of the buttermilk mixture, scraping sides of bowl.\", \"On low speed, beat in the remaining flour mixture until well combined (batter may look curdled).\", \n\"Pour into prepared pan and bake until cake starts to pull away from the sides of the pan, the top is golden brown and a toothpick inserted in the center of the cake comes out clean, 35-40 minutes for bundt or tube pan, or 65-70 minutes for loaf pan.\", \"Cool on rack 10-15 minutes; invert pan and unmold onto rack to cool completely.\", \"Cut into 12 slices.\")"
    },
    {
        "Unnamed: 0": 1467,
        "RecipeId": 2923,
        "Name": "7-Up Pound Cake",
        "CookTime": "PT1H",
        "PrepTime": "PT15M",
        "TotalTime": "PT1H15M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/29/23/pic9OVA7E.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1 1/2\", \"3\", \"5\", \"3\", \"1\", \"3/4\")",
        "RecipeIngredientParts": "c(\"butter\", \"margarine\", \"sugar\", \"eggs\", \"cake flour\")",
        "Calories": 556.9,
        "FatContent": 25.3,
        "SaturatedFatContent": 15.3,
        "CholesterolContent": 138.5,
        "SodiumContent": 234.8,
        "CarbohydrateContent": 78.4,
        "FiberContent": 0.6,
        "SugarContent": 51.5,
        "ProteinContent": 5.7,
        "RecipeInstructions": "c(\"Preheat oven to 300F and grease/flour a tube pan.\", \"Cream butter and sugar together until light and fluffy.\", \"Add eggs one at a time, beating after each one.\", \"Add flour alternating with 7-Up; stir in lemon  flavoring.\", \"Bake in prepared pan until cake tests done, approximately an hour.\")"
    },
    {
        "Unnamed: 0": 174208,
        "RecipeId": 182205,
        "Name": "Cake Mix Apple Pie Cake",
        "CookTime": "PT30M",
        "PrepTime": "PT20M",
        "TotalTime": "PT50M",
        "Images": "\"https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/18/22/05/picoqoXuv.jpg\"",
        "RecipeCategory": "Dessert",
        "RecipeIngredientQuantities": "c(\"1\", \"1/3\", \"2\", \"1/2\", \"1\", \"1\", \"1\", \"1/2\", NA)",
        "RecipeIngredientParts": "c(\"eggs\", \"water\", \"margarine\", \"powdered sugar\", \"vanilla\", \"hot water\")",
        "Calories": 4191.2,
        "FatContent": 151.2,
        "SaturatedFatContent": 23.5,
        "CholesterolContent": 372.0,
        "SodiumContent": 4042.5,
        "CarbohydrateContent": 686.2,
        "FiberContent": 10.7,
        "SugarContent": 486.4,
        "ProteinContent": 36.9,
        "RecipeInstructions": "c(\"Preheat oven to 350 degrees.\", \"Mix together the following ingredients: cake mix, eggs, water, and oil. Pour mixture into a greased 9x13-inch pan. Marble in apple filling.\", \"Bake 30-35 minutes.\", \"Combine margarine, powdered sugar, hot water and vanilla. Drizzle glaze over cake.\")"
    }
]

export default val;